<Project>

    <PropertyGroup>
        <VersionPrefix>0.1.0</VersionPrefix>
        <VersionSuffix>beta.1</VersionSuffix>
        <AssemblyVersion>0.1.0.0</AssemblyVersion>
        <FileVersion>0.1.0.0</FileVersion>
        <Product>New Eridu Proxy</Product>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/touka2014/NewEriduProxy</RepositoryUrl>
        <PackageProjectUrl>https://github.com/touka2014/NewEriduProxy</PackageProjectUrl>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <Nullable>annotations</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Authors>Touka and v2rayN contributors</Authors>
        <PackageLicenseExpression>GPL-3.0</PackageLicenseExpression>
        <Copyright>Copyright © 2017-$([System.DateTime]::UtcNow.Year) $(Authors)</Copyright>
        <InvariantGlobalization>false</InvariantGlobalization>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>embedded</DebugType>
        <EventSourceSupport>false</EventSourceSupport>
        <StackTraceSupport>false</StackTraceSupport>
        <MetricsSupport>false</MetricsSupport>
        <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
        <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
        <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>

        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishReadyToRun>false</PublishReadyToRun>
    </PropertyGroup>
</Project>
